name: Check Execution
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Check Notebook Execution
    steps:
      - uses: actions/checkout@v2
      - name: Test Execution
        run: |
          conda install python==3.7 -y
          python -m pip install notebook rdkit-pypi markupsafe==2.0.1
          jupyter nbconvert --to script ArClOTs_analysis.ipynb
          ipython ArClOTs_analysis.py
