name: Check Execution
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Check Notebook Execution
    steps:
      - uses: actions/checkout@v2
        name: Checkout Latest Changes
          
      - name: Install Dependencies
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
        run: |
          python -m pip install notebook
          
      - name: Convert Notebook to Executable
        run: |
          jupyter nbconvert --to script ArClOTs_analysis.ipynb
      
      - name: Execute Notebook Script
        run: |
          ipython ArClOTs_analysis.py
